#!/bin/sh

BASEDIR="$( cd "$( dirname "$0" )" && pwd )"
ROOTDIR="$( dirname "$BASEDIR" )"

PATH=$ROOTDIR/utils:/usr/bin/local:/usr/bin:/bin

set -e

export LC_ALL=C

both=" 	hello world
foo

bar

 	"

right="hello world
foo

bar

 	"

left=" 	hello world
foo

bar"

none="hello world
foo

bar"


# "  ...  " -> "..."
assert "$(trim "$both")" "$none"
assert "$(printf "$both" | trim)" "$none"

# "  ..." -> "..."
assert "$(trim "$left")" "$none"
assert "$(printf "$left" | trim)" "$none"

# "...  " -> "..."
assert "$(trim "$right")" "$none"
assert "$(printf "$right" | trim)" "$none"

# "..." -> "..."
assert "$(trim "$none")" "$none"
assert "$(printf "$none" | trim)" "$none"
