#!/bin/sh

# strip whitespace from the beginning and end of string.
#
# ' '	space character
# \f	form feed
# \n	new-line
# \r	carriage return
# \t	horizontal tab
# \v	vertical tab

PATH=/usr/bin/local:/usr/bin:/bin

if [ -n "$1" ]; then
	string="$1"
else
	string="$(cat -)"
fi

printf '%s' "$string" | awk '{
	if (NR == 1)
		sub(/^[[:space:]]*/, "")

	if (NR > 1)
		print x

	x=$0
}
END {
	sub(/[[:space:]]*$/, "")
	print
}'
